branch-defaults:
  main:
    environment: Materials-production
global:
  application_name: Materials
  default_ec2_keyname: brett
  profile: default
  default_platform: Docker running on 64bit Amazon Linux 2023
  default_region: ap-northeast-1
  include_git_submodules: true
  platform_name: Docker AL2023
  sc: git
  workspace_type: Application
deploy:
  artifact: dockerrun.aws.json
